### ISSUE TITLE
cpp/submod/SetCover.cpp does not build for C++20

### ISSUE THREAD

**Issue by nab170130** [decile-team/submodlib#1]
The C++ implementation of the SetCover function uses the word 'concept' regularly as a variable name; however, 'concept' is a reserved keyword for C++20 and causes compilation issues during pip installation.

**Comment by vishkaush** [comment]
Removed occurence of "concept" in CPP codebase. Commit bf73bf6a06ec83aa58f6e8fec685a87da23a98cf

**Comment by vishkaush** [comment]
Closed it by mistake. Pls verify if pip install goes through now and close this issue after verification.

**Comment by nab170130** [comment]
The concept keyword issue is resolved; however, there are other compilation issues. I will open a new issue to discuss them.
