### ISSUE TITLE
ERROR: Could not build wheels for submodlib, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by InstantWindy** [decile-team/submodlib#33]
Installation environment:

- python 3.8
- torch 1.4
- cuda 100
- GCC 4.9.3

Error:
`   /tmp/pip-build-env-m7fawz9p/overlay/lib/python3.8/site-packages/pybind11/include/pybind11/numpy.h:1195:51: error: ‘is_pod_struct’ is not a member of ‘pybind11::detail’
      /tmp/pip-build-env-m7fawz9p/overlay/lib/python3.8/site-packages/pybind11/include/pybind11/numpy.h:1195:74: error: template argument 1 is invalid
       struct compare_buffer_info<T, detail::enable_if_t<detail::is_pod_struct<T>::value>> {
                                                                                ^
      /tmp/pip-build-env-m7fawz9p/overlay/lib/python3.8/site-packages/pybind11/include/pybind11/numpy.h:1195:77: error: template argument 2 is invalid
       struct compare_buffer_info<T, detail::enable_if_t<detail::is_pod_struct<T>::value>> {
                                                                                   ^
      /tmp/pip-build-env-m7fawz9p/overlay/lib/python3.8/site-packages/pybind11/include/pybind11/numpy.h:1195:82: error: expected unqualified-id before ‘>’ token
       struct compare_buffer_info<T, detail::enable_if_t<detail::is_pod_struct<T>::value>> {
                                                                                        ^
      /tmp/pip-build-env-m7fawz9p/overlay/lib/python3.8/site-packages/pybind11/include/pybind11/numpy.h:1392:19: error: ‘is_pod_struct’ was not declared in this scope
           static_assert(is_pod_struct<T>::value,
                         ^
      /tmp/pip-build-env-m7fawz9p/overlay/lib/python3.8/site-packages/pybind11/include/pybind11/numpy.h:1392:34: error: expected primary-expression before ‘>’ token
           static_assert(is_pod_struct<T>::value,
                                        ^
      /tmp/pip-build-env-m7fawz9p/overlay/lib/python3.8/site-packages/pybind11/include/pybind11/numpy.h:1392:35: error: ‘::value’ has not been declared
           static_assert(is_pod_struct<T>::value,
                                         ^
      cpp/submod/FacilityLocation2.cpp: In member function ‘void FacilityLocation2::pybind_init(ll, const pybind11::array_t<float>&, bool, const std::unordered_set<long long int>&, bool)’:
      cpp/submod/FacilityLocation2.cpp:77:30: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
           for (size_t idx = 0; idx < num_rows; idx++) {
                                    ^
      cpp/submod/FacilityLocation2.cpp:78:34: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
               for (size_t idy = 0; idy < num_columns; idy++) {
                                        ^
      In file included from cpp/submod/FacilityLocation2.cpp:10:0:
      cpp/submod/FacilityLocation2.h: In constructor ‘FacilityLocation2::FacilityLocation2(ll, const std::vector<std::vector<float> >&, bool, const std::unordered_set<long long int>&, bool)’:
      cpp/submod/FacilityLocation2.h:39:33: warning: ‘FacilityLocation2::denseKernel’ will be initialized after [-Wreorder]
        std::vector<std::vector<float>>denseKernel; //size n_master X n
                                       ^
      cpp/submod/FacilityLocation2.h:32:7: warning:   ‘bool FacilityLocation2::partial’ [-Wreorder]
        bool partial; //if masked implementation is desired, relevant to be used in ClusteredFunction
             ^
      cpp/submod/FacilityLocation2.cpp:125:1: warning:   when initialized here [-Wreorder]
       FacilityLocation2::FacilityLocation2(ll n_, std::vector<std::vector<float>> const &denseKernel_, bool partial_, std::unordered_set<ll> const &ground_, bool separateMaster_): n(n_), mode(dense), denseKernel(denseKernel_), partial(partial_), separateMaster(separateMaster_)  {
       ^
      In file included from cpp/submod/FacilityLocation2.cpp:10:0:
      cpp/submod/FacilityLocation2.h: In constructor ‘FacilityLocation2::FacilityLocation2(ll, const std::vector<std::unordered_set<long long int> >&, const std::vector<std::vector<std::vector<float> > >&, const std::vector<long long int>&)’:
      cpp/submod/FacilityLocation2.h:47:17: warning: ‘FacilityLocation2::clusterIndexMap’ will be initialized after [-Wreorder]
        std::vector<ll>clusterIndexMap; //mapping from datapont index to index in cluster kernel, size = n
                       ^
      In file included from cpp/submod/FacilityLocation2.cpp:10:0:
      cpp/submod/FacilityLocation2.h:32:7: warning:   ‘bool FacilityLocation2::partial’ [-Wreorder]
        bool partial; //if masked implementation is desired, relevant to be used in ClusteredFunction
             ^
      cpp/submod/FacilityLocation2.cpp:228:1: warning:   when initialized here [-Wreorder]
       FacilityLocation2::FacilityLocation2(ll n_, std::vector<std::unordered_set<ll>> const &clusters_,std::vector<std::vector<std::vector<float>>> const &clusterKernels_, std::vector<ll> const &clusterIndexMap_): n(n_), mode(clustered), num_clusters(clusters_.size()), clusters(clusters_), clusterKernels(clusterKernels_), clusterIndexMap(clusterIndexMap_), partial(false), separateMaster(false) {
       ^
      In file included from cpp/submod/FacilityLocation2.cpp:10:0:
      cpp/submod/FacilityLocation2.h: In copy constructor ‘FacilityLocation2::FacilityLocation2(const FacilityLocation2&)’:
      cpp/submod/FacilityLocation2.h:39:33: warning: ‘FacilityLocation2::denseKernel’ will be initialized after [-Wreorder]
        std::vector<std::vector<float>>denseKernel; //size n_master X n
                                       ^
      cpp/submod/FacilityLocation2.h:32:7: warning:   ‘bool FacilityLocation2::partial’ [-Wreorder]
        bool partial; //if masked implementation is desired, relevant to be used in ClusteredFunction
             ^
      cpp/submod/FacilityLocation2.cpp:268:1: warning:   when initialized here [-Wreorder]
       FacilityLocation2::FacilityLocation2(const FacilityLocation2& f)
       ^
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for submodlib
Failed to build submodlib
ERROR: Could not build wheels for submodlib, which is required to install pyproject.toml-based projects
`
So how to tackle it?

**Comment by surajkothawade** [comment]
It looks like the C++ files required for submodlib were not built successfully.

Can you please try with GCC 5.2 or greater and ensure that the pybind11 version you have satisfies requirements.txt?

**Comment by InstantWindy** [comment]
I update the version of GCC, then successfully. Thanks.
