### ISSUE TITLE
Issue installing submodlib library in new environment

### ISSUE THREAD

**Issue by kasuba-badri-vishal** [decile-team/submodlib#36]
While Installing submodlib with the provided alternative 1 is causing the following error

```
    ERROR: Command errored out with exit status 1:
     command: /home/venkat/BADRI/venv/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-vdi9e14s/sklearn/setup.py'"'"'; __file__='"'"'/tmp/pip-install-vdi9e14s/sklearn/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-vdi9e14s/sklearn/pip-egg-info
         cwd: /tmp/pip-install-vdi9e14s/sklearn/
    Complete output (18 lines):
    The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
    rather than 'sklearn' for pip commands.
    
    Here is how to fix this error in the main use cases:
    - use 'pip install scikit-learn' rather than 'pip install sklearn'
    - replace 'sklearn' by 'scikit-learn' in your pip requirements files
      (requirements.txt, setup.py, setup.cfg, Pipfile, etc ...)
    - if the 'sklearn' package is used by one of your dependencies,
      it would be great if you take some time to track which package uses
      'sklearn' instead of 'scikit-learn' and report it to their issue tracker
    - as a last resort, set the environment variable
      SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True to avoid this error
    
    More information is available at
    https://github.com/scikit-learn/sklearn-pypi-package
    
    If the previous advice does not cover your use case, feel free to report it at
    https://github.com/scikit-learn/sklearn-pypi-package/issues/new
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

Please update to the usage of ```scikit-learn``` instead of ```sklearn``` to bypass the error

**Comment by kasuba-badri-vishal** [comment]
Also tried with alternative 2 approach to install submodlib library in local, failing again with multiple errors. Tried installing in various system environments and settings, but did not work. Kindly please update the dependency packages or let me know any issues that I have to address in my environment. Thanks

**Comment by surajkothawade** [comment]
This seems to be an issue with an outdated version of sklearn. Can you please try to update to scikit-learn and retry installation?
Please also make sure to use the latest pip version.

**Comment by kasuba-badri-vishal** [comment]
Upgraded the pip library to the latest version(23.01) and also installed the latest version of scikit-learn library package. Receiving the following error now while installation - [link](https://pastebin.com/G3RgQGtE). The earlier issue might be the reason of outdated pip library.

**Comment by surajkothawade** [comment]
This seems to be an issue due to using an outdated or incompatible version of python.
Pybind11 is not able to find Python.h
Please refer to this GitHub issue from Pybind to find a resolution based on your OS: https://github.com/pybind/pybind11/issues/1728

**Comment by kasuba-badri-vishal** [comment]
Hi @surajkothawade , Following the above issue link helped in solving the problem. This is the [link](https://stackoverflow.com/questions/72502292/fatal-error-python-h-no-such-file-or-directory-when-compiling-pybind11-example) present in the comments which helped in solving my issue. Thanks for the help.
